In [3]:
%%time
#Used to calculate total operation time
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
    


Wall time: 200 ms


In [5]:
%%time
#Used to calculate total operation time
#Importing Numpy
import numpy as np
#Creating a numpy array of 1 million numbers
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b

Wall time: 6.91 ms


In [6]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr


array([78, 92, 36, 64, 89])

In [7]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(student_marks_arr)


[78 92 36 64 89]


In [8]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print(horsepower_arr)

[130 165 150 150 140]


In [9]:
ForCheckingPurpose = ["Hii", 1,2,3, 'r']
FCP_arr = np.array(ForCheckingPurpose)
print(FCP_arr)

['Hii' '1' '2' '3' 'r']


In [10]:
ForCheckingPurpose = [0,"Hii", 1,2,3, 'r']
FCP_arr = np.array(ForCheckingPurpose)
print(FCP_arr)

['0' 'Hii' '1' '2' '3' 'r']


In [11]:
#2D array implementation
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from car_attributes list
car_attributes_arr = np.array(car_attributes)
print(car_attributes_arr)


[[ 18  15  18  16  17]
 [130 165 150 150 140]
 [307 350 318 304 302]]


In [12]:
#how to get shape of the Numpy 2D array?
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape

(3, 5)

In [13]:
#how to get shape of the Numpy 1D array?
car_attributes = [18, 15, 18, 16, 17]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape

(5,)

In [14]:
#how to get shape of the Numpy 1D array?
car_attributes = [18, 15, 18, 16, 17]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
print(car_attributes_arr.shape)

(5,)


In [15]:
#creating a list of lists i.e. 2D array
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype


dtype('int32')

In [16]:
#For checking Purpose- 1
car_attributes = [18, 15, 'hii', 18, 16, 17]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype

dtype('<U11')

In [17]:
#For checking Purpose- 2 
car_attributes = ['18', 'll', 'hii', '18', '16', '17']
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype

dtype('<U3')

In [18]:
#For checking Purpose -3
car_attributes = ["h", "hi", "hii", "hiii", "hiiii"]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype

dtype('<U5')

In [19]:
#creating a list of lists 
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#converting dtype
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [20]:
#For checking Purpose -4
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#converting dtype
car_attributes_arr = np.array(car_attributes, dtype = 'string')
print(car_attributes_arr)
print(car_attributes_arr.dtype)


TypeError: data type 'string' not understood

In [21]:
#For checking Purpose -4
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#converting dtype
car_attributes_arr = np.array(car_attributes, dtype = 'str')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[['18' '15' '18' '16' '17']
 ['130' '165' '150' '150' '140']
 ['307' '350' '318' '304' '302']]
<U3


In [22]:
# change the dtype to 'float64'
arr = car_attributes_arr.astype('float64')  #new method
print(arr)
print(arr.dtype)



[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64
